version: '3.8'

services:
  postgres-baliair:
    image: postgres:15
    container_name: baliair-postgres
    ports:
      - "5436:5432"  # Host port 5436 → Container port 5432
    environment:
      POSTGRES_DB: bali_air_db
      POSTGRES_USER: bali_user
      POSTGRES_PASSWORD: bali_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baliair-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres-baliair
    environment:
      SPRING_PROFILES_ACTIVE: docker  # Activate docker profile

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: kafka-zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka-broker
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes

volumes:
  postgres_data:
