version: '3.8'

services:
  postgres-baliair:
    image: postgres:15
    container_name: baliair-postgres
    ports:
      - "5436:5432"  # Map host port 5436 to container port 5432
    environment:
      POSTGRES_DB: bali_air_db
      POSTGRES_USER: bali_user
      POSTGRES_PASSWORD: bali_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

